# Generated by Django 3.2.6 on 2021-08-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_app', '0009_auto_20210810_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title_uk',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests_app.option'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='answers',
            field=models.ManyToManyField(related_name='sessions', to='tests_app.Answer'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
